wandb_version: 1

model:
  desc: null
  value: Model 3
save_weights:
  desc: null
  value: true
import_weights:
  desc: null
  value: false
save_images:
  desc: null
  value: true
train:
  desc: null
  value: true
test:
  desc: null
  value: true
epochs:
  desc: null
  value: 200
learning_rate:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: Adam
criterion:
  desc: null
  value: MSE
data_set:
  desc: null
  value: data/Captioning/
split:
  desc: null
  value: 0.25
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685308750.830737
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.16
      5: 0.15.2
      8:
      - 5
